### PR TITLE
Update to alpine 3.12

### PR DESCRIPTION
**Pull request by murdos**

### CODE REVIEW

**Comment by murdos** [comment]
@pascalgrimaud : could you do a release once this PR is merged?

**Comment by pascalgrimaud** [comment]
@murdos : ok

**Comment by pascalgrimaud** [comment]
@murdos : done - see https://github.com/jhipster/consul-config-loader/releases/tag/v0.4.0

**Comment by murdos** [comment]
Awesome, thanks! 😄

**Pull request merged**
