### PR TITLE
Update consul to 1.4.0

### PR DESCRIPTION
**Pull request by DanielFran**
See https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#140-november-14-2018

### CODE REVIEW

**Comment by DanielFran** [comment]
@PierreBesson Can you check if it is OK?

**Comment by DanielFran** [comment]
@PierreBesson Maybe with this new version you might take a look and restore the ACL?
See https://www.consul.io/docs/upgrade-specific.html#consul-1-4-0

**Comment by PierreBesson** [comment]
@DanielFran Oh it looks complex and now they seem to have changed the api so I don't know if it work with the consul client used by spring-cloud-consul. I have no time to dig into that not being a user of Consul myself. It would be nice if actual users would come forward to improve support. In the mean time I can only maintain basic support for Consul so ACLs will complicate things a lot.

**Comment by PierreBesson** [comment]
@DanielFran I have given you write access to this repo. Can you do a release and wait a bit to see the docker image automatically pushed to docker hub.

**Pull request merged**
